1.20.41--FeaturedOffers
teamauthenteak/authenteak.com pull request #67
Opened 2021-08-06 17:33 UTC by rickeydute

-FO page is on template__b
-Added code for a collapsible sticky menu for the FO small tablet and mobile page.
-Changed the size of the Nosto carets from 35px x 84px to 12px x 23px.
-Created a new class to override some Nosto stylings.
-Removed the lazy-load from the Clyde modal to force the images to load on cart load.
-Removed a sentence from the 404 page per Alix's request.

2021-08-09 13:53 UTC, teamteak approved these changes

2021-08-09 13:53 UTC, teamteak commented on assets/scss/components/_generics.scss
> +.navHeight-2{
This is not a meaningful class name.  why are there two?

2021-08-09 13:53 UTC, teamteak commented on assets/scss/components/_generics.scss
> +.sticky-2{
This is not a meaningful class name.  why are there two?

2021-08-09 20:02 UTC, rickeydute commented on assets/scss/components/_generics.scss
> +.sticky-2{
navHeight was added to work with the sticky menu on the Shipping Policy page.
navHeight-2 was added for the sticky menu for the Featured Offers page. 
Unfortunately, the Shipping Policy is so tall that using this on the FO page makes the page very long and adds a lot of extra whitespace after the content is finished so a new class to accommodate the length of the FO page.

2021-08-10 12:25 UTC, teamteak commented on assets/scss/components/_generics.scss
> +.sticky-2{
the classes need to convey meaning, aka, what does the class mean? adding a -2 isn't a good way to create classes as it doesn't indicate what its use would be more where it's used.

2021-08-10 12:27 UTC, teamteak requested changes
Remove the styles for the ID and change it to meaningful classes.

2021-08-10 12:27 UTC, teamteak commented on assets/scss/templates/_product.scss
> +#pdf a:link {
We don't style IDs .  Only classes

2021-08-10 12:27 UTC, teamteak commented on assets/scss/templates/_product.scss
> +#pdf a:link {
This needs to be fixed

2021-08-10 16:49 UTC, rickeydute commented on assets/scss/components/_generics.scss
> +.sticky-2{
Ok. I'll keep that in mind for the next time. I'll switch them and release an update at the end of the sprint to not hold up this release any longer.

2021-08-10 17:42 UTC, teamteak approved these changes

2021-08-10 17:42 UTC, merged